version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: marketflow-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: marketflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  exchange1:
    image: exchange1:latest
    container_name: exchange1
    ports:
      - "40101:40101"

  exchange2:
    image: exchange2:latest
    container_name: exchange2
    ports:
      - "40102:40102"

  exchange3:
    image: exchange3:latest
    container_name: exchange3
    ports:
      - "40103:40103"

volumes:
  postgres_data: